[agent]
  interval = "10s"
  round_interval = true

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  timeout = "5s"

[[outputs.prometheus_client]]
  listen = ":9273"
